# Generated by Django 2.1.5 on 2022-06-16 11:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='vote',
            field=models.ManyToManyField(blank=True, default=0, related_name='companies_vote', to=settings.AUTH_USER_MODEL),
        ),
    ]
